packageExtensions:
  "@nestjs/swagger@^5.1.0":
    peerDependencies:
      class-transformer: "*"
      class-validator: "*"
      typescript: ^4.4.3
  "@nuxt/babel-preset-app@^2.15.8":
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": ^7.15.4
      debug: ^4.3.2
      encoding: ^0.1.13
      supports-color: ^9.0.2
  "@nuxt/typescript-build@^2.1.0":
    peerDependencies:
      vue-template-compiler: ^2.6.14
      webpack: ^4.4.3
  "@nuxtjs/eslint-config-typescript@^6.0.1":
    peerDependencies:
      typescript: ^4.4.3
  "@typescript-eslint/experimental-utils@^4.32.0":
    peerDependencies:
      typescript: ^4.4.3
  "@typescript-eslint/typescript-estree@^4.32.0":
    peerDependencies:
      typescript: ^4.4.3
  eslint-plugin-jest@^24.5.0:
    peerDependencies:
      typescript: ^4.4.3
  "@fastify/cookie@^6.0.0":
    peerDependencies:
      fastify: ^3.22.0
  "@fastify/helmet@^8.0.0":
    peerDependencies:
      fastify: ^3.22.0
  "@fastify/multipart@^6.0.0":
    peerDependencies:
      fastify: ^3.22.0
  middie@*:
    dependencies:
      fastify: "*"
  nuxt@*:
    peerDependencies:
      consola: "*"
  run-script-webpack-plugin@^0.0.11:
    peerDependencies:
      webpack: ^4.4.3
  vue-eslint-parser@*:
    dependencies:
      "@typescript-eslint/parser": "*"
      typescript: ^4.4.3
  nestjs-throttler-storage-redis@^0.1.18:
    dependencies:
      "ioredis": ^4.28.5

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
